apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-deployment.fullname" . }}-wordpress-mysql
  labels:
    app: wordpress
  {{- include "mysql-deployment.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
    {{- include "mysql-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
      {{- include "mysql-deployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.wordpressMysql.mysql.image.repository }}:{{ .Values.wordpressMysql.mysql.image.tag
          | default .Chart.AppVersion }}
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "mysql-deployment.fullname" . }}-mysql-pv-claim