apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-deployment.fullname" . }}-ordpress
  labels:
    app: wordpress
  {{- include "wordpress-deployment.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
    {{- include "wordpress-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
      {{- include "wordpress-deployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-pass
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.ordpress.wordpress.image.repository }}:{{ .Values.ordpress.wordpress.image.tag
          | default .Chart.AppVersion }}
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wordpress-deployment.fullname" . }}-p-pv-claim