apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-deployment.fullname" . }}-p-pv-claim
  labels:
    app: wordpress
  {{- include "wordpress-deployment.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pPvClaim.storageRequest | quote }}